apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T07:29:34Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3153"
  uid: 1f128c81-ea92-4f39-b605-baa81261d0cd
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.106.255.75
  clusterIPs:
  - 10.106.255.75
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31055
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}